# Generated by Django 4.2.6 on 2023-10-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_group_id', models.IntegerField(default=0, null=True)),
                ('manager_id', models.CharField(max_length=45, null=True)),
                ('name', models.CharField(max_length=45, null=True)),
                ('phone', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=200)),
                ('otp_info', models.TextField(default=0)),
                ('personal_access_tokens', models.CharField(max_length=100)),
                ('permission_function', models.TextField()),
                ('permissions_menu', models.TextField()),
                ('permissions_site', models.TextField()),
                ('role_code', models.CharField(max_length=6)),
                ('admin_status_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('password_changed', models.DateTimeField(auto_now=True)),
                ('use_yn', models.CharField(max_length=1)),
                ('note', models.CharField(max_length=45)),
                ('admin_id', models.IntegerField()),
                ('admin_board_noti', models.TextField()),
                ('utc', models.CharField(max_length=10)),
                ('Lang', models.CharField(max_length=2)),
                ('logout_time', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
    ]
